name: Our CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Second step
        run: |
          echo "Hello world"
          mkdir mydir
          ls -la
